spring:
  datasource:
    username: root
    password: HDTMsrszq01~
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    logging:
      level:
        com.ptu.mall.mapper: debug
      pattern:
        dateformat: HH:mm:ss
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  type-aliases-package: com.ptu.mall.domain.po
  global-config:
    db-config:
      logic-delete-field: isDel
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: "classpath*:/mapper/**/*.xml"
